### ISSUE TITLE
patch_code failing to apply on crDroid

### ISSUE THREAD

**Issue by mmtrt** [chenxiaolong/aosproot#4]
```
 -> aosproot patch_code
Applying /root/aosp/crd13/vendor/aosproot/patches/build/make/0001-Apply-Magisk-patch-to-boot-image.patch in /root/aosp/crd13/build/make
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
Traceback (most recent call last):
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 86, in _run_code
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/__main__.py", line 12, in <module>
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 86, in _run_code
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/aosproot.py", line 129, in <module>
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/aosproot.py", line 123, in main
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/aosproot.py", line 84, in patch_code
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['git', '-C', '/root/aosp/crd13/build/make', 'am', '/root/aosp/crd13/vendor/aosproot/patches/build/make/0001-Apply-Magisk-patch-to-boot-image.patch']' returned non-zero exit status 128.
```

**Comment by chenxiaolong** [comment]
What does `git status` inside `build/make/` look like? Based on that error, it seems like you might need to cancel a rebase with `git rebase --abort` (and possible sync the repos again).

**Comment by mmtrt** [comment]
looks like this,
```
➜  make git:(5465713) git status
Not currently on any branch.
You are in the middle of an am session.
  (fix conflicts and then run "git am --continue")
  (use "git am --skip" to skip this patch)
  (use "git am --abort" to restore the original branch)

nothing to commit, working tree clean
```

**Comment by mmtrt** [comment]
resynced and retrying failed again. [diff](https://paste.myself5.de/sinozakedu.sql)

```
➜  crd13 aosproot patch_code
Applying /root/aosp/crd13/vendor/aosproot/patches/build/make/0001-Apply-Magisk-patch-to-boot-image.patch in /root/aosp/crd13/build/make
Applying: Apply Magisk patch to boot image
error: patch failed: core/Makefile:5111
error: core/Makefile: patch does not apply
Patch failed at 0001 Apply Magisk patch to boot image
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Traceback (most recent call last):
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 86, in _run_code
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/__main__.py", line 12, in <module>
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/runpy.py", line 86, in _run_code
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/aosproot.py", line 129, in <module>
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/aosproot.py", line 123, in main
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/aosproot.py", line 84, in patch_code
  File "/root/aosp/crd13/out/host/linux-x86/bin/aosproot/internal/stdlib/subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['git', '-C', '/root/aosp/crd13/build/make', 'am', '/root/aosp/crd13/vendor/aosproot/patches/build/make/0001-Apply-Magisk-patch-to-boot-image.patch']' returned non-zero exit status 128.

```

**Comment by chenxiaolong** [comment]
Ah, I wonder if the ROM you're building has some small changes to `core/Makefile` compared to AOSP. `git am` will fail to apply a patch if the diff doesn't match exactly.

I'd suggest applying the patch manually:

```bash
cd build/make
git am --abort
patch -p1 -i ../../vendor/aosproot/patches/build/make/0001-Apply-Magisk-patch-to-boot-image.patch
```

**Comment by mmtrt** [comment]
fixed patch & applied manually, build fails now
https://paste.myself5.de/enuwacubud

**Comment by chenxiaolong** [comment]
Try replacing:
```
if info_dict['init_boot'] == 'true':
```
with:
```
if info_dict.get('init_boot') == 'true':
```

**Comment by mmtrt** [comment]
still failing, even tho magisk apk is present.
https://paste.myself5.de/eretirimuh
